# general plugin configuration

# colour scheme for messages sent to players
colour-scheme:
  normal: gray
  error: red
  highlight: yellow
  prefix: dark_green

# politics economy functions configuration
economic:
  enabled: true
  economy-type: vault
