# general plugin configuration

# colour scheme for messages sent to players
colour-scheme:
  normal: gray
  error: red
  highlight: yellow
  prefix: dark_green

# wars configuration
wars:
  enabled: false

# politics economy functions configuration
economic:
  enabled: true
  economy-type: vault
  tax: false
  max-fixed-tax: 10
  tax-period: 1440 # minutes
